language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
install:
- "yarn install"
before_script:
- npm install -g grunt-cli
script:
- "yarn deploy"
after_script:
- grunt retire
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
